(function () {
  "use strict";
  const departmentPage = document.querySelector(".department-layout");
  if (!departmentPage) return;
  Site.onReady(function () {
    const departmentButtons = Array.from(departmentPage.querySelectorAll(".department-select")); const detail = departmentPage.querySelector(".department-detail"); const facultyList = document.getElementById("faculty-list"); const modal = document.querySelector(".faculty-modal"); const closeModal = modal && modal.querySelector(".faculty-modal-close"); let currentDepartment = "Botany"; let facultyRecords = []; let lastFocusedFacultyCard = null;
    const normalize = function (value) { return String(value || "").toLowerCase().replace(/^department\s+of\s+/, "").replace(/\s*&\s*/g, " and ").replace(/[^a-z0-9]+/g, " ").trim(); };
    const parseFaculty = function (text) { return Site.parseKeyValueBlocks(text).filter(function (record) { return record.faculty_profile_number; }); };
    const openFaculty = function (record, opener) { if (!modal) return; lastFocusedFacultyCard = opener; modal.querySelector("#faculty-modal-title").textContent = record.Name || "Faculty profile"; const fields = ["Department", "Designation", "Qualification", "Teaching Experience", "Academic Positions", "Areas of Interest", "Contact"]; const definitionList = modal.querySelector("dl"); definitionList.replaceChildren(); fields.forEach(function (field) { if (record[field]) { const term = document.createElement("dt"); const value = document.createElement("dd"); term.textContent = field; value.textContent = record[field]; definitionList.append(term, value); } }); modal.hidden = false; document.body.classList.add("modal-open"); if (closeModal) closeModal.focus(); };
    const renderFaculty = function () {
      if (!facultyList) return; facultyList.replaceChildren(); const matches = facultyRecords.filter(function (record) { return normalize(record.Department).includes(normalize(currentDepartment)) || normalize(currentDepartment).includes(normalize(record.Department)); });
      if (!matches.length) { const empty = document.createElement("p"); empty.className = "muted"; empty.textContent = "Faculty profiles will be added when official records are supplied."; facultyList.appendChild(empty); return; }
      matches.forEach(function (record) { const card = document.createElement("button"); card.type = "button"; card.className = "faculty-card"; const photo = document.createElement("span"); photo.className = "faculty-photo"; photo.setAttribute("role", "img"); photo.setAttribute("aria-label", "Photograph of " + (record.Name || "faculty member")); const image = document.createElement("img"); image.alt = ""; const extensions = ["jpg", "jpeg", "png", "webp"]; let extensionIndex = 0; image.src = Site.pageBase + "assets/images/faculty_profile_images/" + record.faculty_profile_number + "." + extensions[extensionIndex]; image.onerror = function () { extensionIndex += 1; if (extensionIndex < extensions.length) image.src = Site.pageBase + "assets/images/faculty_profile_images/" + record.faculty_profile_number + "." + extensions[extensionIndex]; else { image.remove(); photo.classList.add("missing-image"); } }; photo.appendChild(image); const details = document.createElement("span"); details.innerHTML = "<strong></strong><small></small>"; details.firstElementChild.textContent = record.Name || "Faculty profile"; details.lastElementChild.textContent = record.Designation || "Designation to be supplied"; card.append(photo, details); card.addEventListener("click", function () { openFaculty(record, card); }); facultyList.appendChild(card); });
    };
    departmentButtons.forEach(function (button) { button.addEventListener("click", function () { departmentButtons.forEach(function (item) { item.classList.toggle("is-selected", item === button); }); currentDepartment = button.textContent.trim(); detail.querySelector(".department-title").textContent = currentDepartment; renderFaculty(); }); });
    departmentPage.querySelectorAll(".department-tab").forEach(function (tab) { tab.addEventListener("click", function () { const panelId = tab.getAttribute("aria-controls"); departmentPage.querySelectorAll(".department-tab").forEach(function (item) { item.classList.toggle("is-active", item === tab); item.setAttribute("aria-selected", String(item === tab)); }); departmentPage.querySelectorAll(".department-panel").forEach(function (panel) { panel.hidden = panel.id !== panelId; panel.classList.toggle("is-active", panel.id === panelId); }); }); });
    const dismissModal = function () { if (modal) { modal.hidden = true; document.body.classList.remove("modal-open"); if (lastFocusedFacultyCard) lastFocusedFacultyCard.focus(); } }; if (closeModal) closeModal.addEventListener("click", dismissModal); if (modal) { modal.addEventListener("click", function (event) { if (event.target === modal) dismissModal(); }); document.addEventListener("keydown", function (event) { if (event.key === "Escape" && !modal.hidden) dismissModal(); }); }
    Site.loadData("data/faculty.txt", "text").then(function (text) { facultyRecords = parseFaculty(text); renderFaculty(); }).catch(function () { facultyRecords = []; renderFaculty(); });
  });
})();
