(function () {
  "use strict";
  const departmentPage = document.querySelector(".department-layout");
  if (!departmentPage) return;
  Site.onReady(function () {
    const departmentButtons = Array.from(departmentPage.querySelectorAll(".department-select")); const detail = departmentPage.querySelector(".department-detail"); const facultyList = document.getElementById("faculty-list"); const modal = document.querySelector(".faculty-modal"); const closeModal = modal && modal.querySelector(".faculty-modal-close"); let currentDepartment = "Botany"; let facultyRecords = []; let lastFocusedFacultyCard = null;
    const normalize = function (value) { return String(value || "").toLowerCase().replace(/^department\s+of\s+/, "").replace(/\s*&\s*/g, " and ").replace(/[^a-z0-9]+/g, " ").trim(); };
    const departmentFolder = function (value) { return normalize(value).split(/\s+/).filter(Boolean).map(function (word) { return word.charAt(0).toUpperCase() + word.slice(1); }).join("-"); };
    const field = function (record, name) { return record[name] || record[name.toLowerCase()] || ""; };
    const parseFaculty = function (text) { return Site.parseKeyValueBlocks(text).filter(function (record) { return record.faculty_profile_number; }); };
    const openFaculty = function (record, opener) { if (!modal) return; lastFocusedFacultyCard = opener; modal.querySelector("#faculty-modal-title").textContent = field(record, "Name") || "Faculty profile"; const fields = ["Department", "Designation", "Qualification", "Teaching Experience", "Academic Positions", "Areas of Interest", "Contact"]; const definitionList = modal.querySelector("dl"); definitionList.replaceChildren(); fields.forEach(function (name) { const valueText = field(record, name); if (valueText) { const term = document.createElement("dt"); const value = document.createElement("dd"); term.textContent = name; value.textContent = valueText; definitionList.append(term, value); } }); modal.hidden = false; document.body.classList.add("modal-open"); if (closeModal) closeModal.focus(); };
    const renderFaculty = function () {
      if (!facultyList) return; facultyList.replaceChildren(); const matches = facultyRecords.filter(function (record) { return normalize(field(record, "Department")).includes(normalize(currentDepartment)) || normalize(currentDepartment).includes(normalize(field(record, "Department"))); });
      if (!matches.length) { const empty = document.createElement("p"); empty.className = "muted"; empty.textContent = "Faculty profiles will be added when official records are supplied."; facultyList.appendChild(empty); return; }
      matches.forEach(function (record) { const card = document.createElement("button"); card.type = "button"; card.className = "faculty-card"; const photo = document.createElement("span"); photo.className = "faculty-photo"; photo.setAttribute("role", "img"); photo.setAttribute("aria-label", "Photograph of " + (field(record, "Name") || "faculty member")); const image = document.createElement("img"); image.alt = ""; const extensions = ["jpg", "jpeg", "png", "webp"]; let extensionIndex = 0; const imageBase = Site.pageBase + "assets/images/faculty_profile_images/" + departmentFolder(field(record, "Department")) + "/" + record.faculty_profile_number; image.src = imageBase + "." + extensions[extensionIndex]; image.onerror = function () { extensionIndex += 1; if (extensionIndex < extensions.length) image.src = imageBase + "." + extensions[extensionIndex]; else { image.remove(); photo.classList.add("missing-image"); } }; photo.appendChild(image); const details = document.createElement("span"); details.innerHTML = "<strong></strong><small></small>"; details.firstElementChild.textContent = field(record, "Name") || "Faculty profile"; details.lastElementChild.textContent = field(record, "Designation") || "Designation to be supplied"; card.append(photo, details); card.addEventListener("click", function () { openFaculty(record, card); }); facultyList.appendChild(card); });
    };
    departmentButtons.forEach(function (button) { button.addEventListener("click", function () { departmentButtons.forEach(function (item) { item.classList.toggle("is-selected", item === button); }); currentDepartment = button.textContent.trim(); detail.querySelector(".department-title").textContent = currentDepartment; renderFaculty(); }); });
    departmentPage.querySelectorAll(".department-tab").forEach(function (tab) { tab.addEventListener("click", function () { const panelId = tab.getAttribute("aria-controls"); departmentPage.querySelectorAll(".department-tab").forEach(function (item) { item.classList.toggle("is-active", item === tab); item.setAttribute("aria-selected", String(item === tab)); }); departmentPage.querySelectorAll(".department-panel").forEach(function (panel) { panel.hidden = panel.id !== panelId; panel.classList.toggle("is-active", panel.id === panelId); }); }); });
    const dismissModal = function () { if (modal) { modal.hidden = true; document.body.classList.remove("modal-open"); if (lastFocusedFacultyCard) lastFocusedFacultyCard.focus(); } }; if (closeModal) closeModal.addEventListener("click", dismissModal); if (modal) { modal.addEventListener("click", function (event) { if (event.target === modal) dismissModal(); }); document.addEventListener("keydown", function (event) { if (event.key === "Escape" && !modal.hidden) dismissModal(); }); }
    Site.loadData("data/faculty.txt", "text").then(function (text) { facultyRecords = parseFaculty(text); renderFaculty(); }).catch(function () { facultyRecords = []; renderFaculty(); });
    const staffTable = document.getElementById("non-teaching-staff");
    if (staffTable) Site.loadData("data/non_teaching_staff.txt", "text").then(function (text) {
      const body = staffTable.querySelector("tbody"); body.replaceChildren();
      Site.parseKeyValueBlocks(text).forEach(function (record) {
        const row = document.createElement("tr");
        ["name", "occupation", "qualification", "experience"].forEach(function (key) { const cell = document.createElement("td"); cell.textContent = record[key] || "Unavailable"; row.appendChild(cell); });
        body.appendChild(row);
      });
      if (!body.children.length) body.innerHTML = "<tr><td colspan=\"4\">Non-teaching staff records are unavailable.</td></tr>";
    }).catch(function () { staffTable.querySelector("tbody").innerHTML = "<tr><td colspan=\"4\">Non-teaching staff records are unavailable.</td></tr>"; });
  });
})();
